# If preset.sh is provided, define it (this is for global_functions.sh):
preset_location="$(dirname $(readlink -f $0))/preset.sh"

if [ -f "$preset_location" ]; then
    use_preset="$preset_location"
fi

source "$(dirname $(readlink -f $0))/global_functions.sh"

efi_directory="$1"

if [ -z "$efi_directory" ]; then
    efi_directory="/boot"
fi

# Set the timezone
echo
echo "${INFO} Setting timezone $timezone${RESET}"
command "ln -sf /usr/share/zoneinfo/$timezone /etc/localtime"
command "hwclock --systohc"

# Set the locale
echo
another_locale="Y"
first="Y"
while [ "$another_locale" == "y" ] || [ "$another_locale" == "Y" ]; do
    unset another_locale

    custom_read " Please enter the locale you want to add (ex. en_US.UTF-8 UTF-8, es_ES.UTF-8 UTF-8)${RESET}" locale
    
    if [ "$first" == "Y" ]; then
        first="N"
        echo "$locale" > /etc/locale.gen
    else
        echo "$locale" >> /etc/locale.gen
    fi

    # If we are running using preset, we don't want to ask for more locales
    if [ ! -z "$use_preset" ]; then
        break
    fi

    ask_yes_no " Do you want to add another locale?" another_locale
    
    unset locale
done

echo
echo "${INFO} Generating locales...${RESET}"
command "locale-gen"

# Keyboard layout
echo
echo "${INFO} Keyboard layout${RESET}"
custom_read " Please enter your keyboard layout (example: es, us)${RESET}" keyboard_layout
echo "KEYMAP=$keyboard_layout" > /etc/vconsole.conf

# Hostname
echo
custom_read " Please enter your hostname${RESET}" hostname
echo "${INFO} Setting hostname $hostname${RESET}"
echo "$hostname" > /etc/hostname
echo "127.0.0.1     localhost" > /etc/hosts
echo "::1           localhost" >> /etc/hosts
echo "127.0.1.1     $hostname.localhost        $hostname" >> /etc/hosts

echo "${INFO} Enabling NetworkManager...${RESET}"
command "systemctl enable NetworkManager"
echo

# Root password
echo "${INFO} Setting root password...${RESET}"
if [ -z "$root_pass" ]; then
    while true; do
        if passwd; then
            break  # Passwords match
        fi
    done
else
    command "echo root:$root_pass | chpasswd"
fi

# User name and password
echo
custom_read " Please enter your username${RESET}" user_name
command "useradd -m $user_name"
echo "${INFO} Setting user password...${RESET}"
if [ -z "$user_pass" ]; then
    while true; do
        if passwd "$user_name"; then
            break  # Passwords match
        fi
    done
else
    command "echo $user_name:$user_pass | chpasswd"
fi

# User groups and sudo
echo "${INFO} Groups and sudo for $user_name...${RESET}"
command "usermod -aG wheel,video,audio,storage $user_name"
command "sed -i '/^#\s*%wheel ALL=(ALL:ALL) ALL/s/^#\s*//' /etc/sudoers"

# Configure wifi for next boot
if [ "$wifi" = "y" ] || [ "$wifi" = "Y" ]; then
    echo "${INFO} Configuring Easy Wifi script for next boot...${RESET}"

    wifi_script_location="$(dirname $(readlink -f $0))/wifi_setup.sh"

    command "cp $wifi_script_location /home/$user_name/wifi_setup.sh"
    command "chmod +x /home/$user_name/wifi_setup.sh"

    echo "" >> /home/$user_name/.bashrc
    echo "# Auto-generated by Adri's Arch Linux Installer Script" >> /home/$user_name/.bashrc
    echo "# Check if the device is connected to any WiFi network" >> /home/$user_name/.bashrc
    echo 'if ! nmcli -t -f ACTIVE,SSID dev wifi | grep -q "^yes:"; then' >> /home/$user_name/.bashrc
    echo "  ./wifi_setup.sh" >> /home/$user_name/.bashrc
    echo "fi" >> /home/$user_name/.bashrc

fi

# GRUB

echo "${INFO} Downloading GRUB...${RESET}"
command "pacman -S grub efibootmgr os-prober --noconfirm"
sed -i 's/#GRUB_DISABLE_OS_PROBER=false/GRUB_DISABLE_OS_PROBER=false/g' /etc/default/grub

echo "${INFO} Installing GRUB...${RESET}"
command "grub-install --target=x86_64-efi --efi-directory=$efi_directory --bootloader-id=GRUB"

echo "${INFO} Generating GRUB configuration...${RESET}"
command "grub-mkconfig -o /boot/grub/grub.cfg"

echo "${INFO} GRUB installed!${RESET}"

# Finish
echo
echo "${INFO} Setup completed!${RESET}"

sleep 1

exit 0
